FROM node:alpine AS build
WORKDIR /client
COPY package.json .
RUN npm i
COPY . .
ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL $REACT_APP_API_BASE_URL
RUN npm run build

FROM nginx
COPY --from=build /client/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]

